### ISSUE TITLE
Fix: csv 파일 읽기 쓰기 로직 수정

### ISSUE THREAD

**Issue by Sangjun-man** [Sangjun-man/CheckMate#2]
# Todo 
- [x] 환경변수에서 파일 경로 읽어오기
- [x] 경로에 파일이 없으면 csv 파일 생성 및 createdAt, count 헤더 추가
- [x] 파일 존재 시 기존 방식처럼 appendLine
